language: python
python:
  - '3.5'
  - '3.6'

install:
  - pip install coveralls codacy-coverage
  - pip install -r requirements.txt
  - pip install -e .

script:
    - python setup.py test

after_success:
    - coveralls
    - coverage xml
    - python-codacy-coverage -r coverage.xml
